const FETCH_NEWS = "FETCH_NEWS";
const UPDATE_NEWS = "UPDATE_NEWS";
const SEARCH_NEWS = "SEARCH_NEWS";
const SHOW_LOADING = "SHOW_LOADING";

export { FETCH_NEWS, UPDATE_NEWS, SEARCH_NEWS, SHOW_LOADING }

