const FETCH_NEWS = "FETCH_NEWS";
const UPDATE_NEWS = "UPDATE_NEWS";
const SEARCH_NEWS = "SEARCH_NEWS";
const SHOW_LOADING = "SHOW_LOADING";
const CHANGE_PAGE = "CHANGE_PAGE";
const SWITCH_LANGUAGE = "SWITCH_LANGUAGE";

export { FETCH_NEWS, UPDATE_NEWS, SEARCH_NEWS, SHOW_LOADING, CHANGE_PAGE, SWITCH_LANGUAGE }